### ISSUE TITLE
r-value needs to be squared 

### ISSUE THREAD

**Issue by jameschristopher** [quantopian/qrisk#4]
https://github.com/quantopian/qrisk/blob/master/qrisk/stats.py#L638

[`linregress` returns the r-value or correlation coefficient.](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html)

The docstring for `stability_of_timeseries` says it returns the r-squared as the stability score, but currently it doesn't look like it is being squared.

**Comment by ahgnaw** [comment]
https://github.com/quantopian/qrisk/blob/travis/qrisk/stats.py#L648
